Lesson2
Pafnodeveloper/gb_django pull request #2
Opened 2021-10-09 16:01 UTC by Pafnodeveloper

2. Поработать с шаблонными тегами и placeholder'ами (заглавные буквы, вывод текущей даты в шаблоне) - добавил дату
5. Поработать со статическими файлами (убрать статическое объявление статики, переделав на динамическое отображение) - не понял, что нужно сделать

2021-10-10 09:23 UTC, Vokler requested changes

2021-10-10 09:23 UTC, Vokler commented on products/fixtures/products.json
> +{"title": "GeekShop - \u041a\u0430\u0442\u0430\u043b\u043e\u0433", "products": [{"name": "\u0425\u0443\u0434\u0438 \u0447\u0435\u0440\u043d\u043e\u0433\u043e \u0446\u0432\u0435\u0442\u0430 \u0441 \u0
В этот файл не нужно выносить весь контекст их контроллера, а только список продуктов.

2021-10-10 09:23 UTC, Vokler commented on products/templates/products/products.html
> +                                {% if product.isAvailable%}
Используйте snake_case вместо camelCase, так как pip Питона говорит, что нужно так

2021-10-10 09:24 UTC, Vokler commented
Насчет 3его задания - просто нужно было загружать статику `{% load static %}` через шаблонный тег. На 1ом уроке у нас были захордкоржены пути

2021-10-10 13:33 UTC, Pafnodeveloper commented on products/templates/products/products.html
> +                                {% if product.isAvailable%}
А какой порядок внесения изменений? Мне нужно создавать новую ветку и делать новый ПР?

2021-10-10 13:34 UTC, Pafnodeveloper commented on products/fixtures/products.json
> +{"title": "GeekShop - \u041a\u0430\u0442\u0430\u043b\u043e\u0433", "products": [{"name": "\u0425\u0443\u0434\u0438 \u0447\u0435\u0440\u043d\u043e\u0433\u043e \u0446\u0432\u0435\u0442\u0430 \u0441 \u0
Ну уж создал уже, ничего страшного

2021-10-11 09:57 UTC, vprinz commented on products/fixtures/products.json
> +{"title": "GeekShop - \u041a\u0430\u0442\u0430\u043b\u043e\u0433", "products": [{"name": "\u0425\u0443\u0434\u0438 \u0447\u0435\u0440\u043d\u043e\u0433\u043e \u0446\u0432\u0435\u0442\u0430 \u0441 \u0
Вынесите лучше, так вы потренируетесь вносить изменения в ветку

2021-10-11 13:45 UTC, Pafnodeveloper commented on products/templates/products/products.html
> +                                {% if product.isAvailable%}
Поправил

2021-10-11 13:45 UTC, Pafnodeveloper commented on products/fixtures/products.json
> +{"title": "GeekShop - \u041a\u0430\u0442\u0430\u043b\u043e\u0433", "products": [{"name": "\u0425\u0443\u0434\u0438 \u0447\u0435\u0440\u043d\u043e\u0433\u043e \u0446\u0432\u0435\u0442\u0430 \u0441 \u0
Чтобы не ломать цикл в products.html  вынес из .json файла только "title"

2021-10-12 09:03 UTC, vprinz commented on products/fixtures/products.json
> +{"title": "GeekShop - \u041a\u0430\u0442\u0430\u043b\u043e\u0433", "products": [{"name": "\u0425\u0443\u0434\u0438 \u0447\u0435\u0440\u043d\u043e\u0433\u043e \u0446\u0432\u0435\u0442\u0430 \u0441 \u0
Про title и говорил)

2021-10-12 09:03 UTC, vprinz approved these changes

2021-10-12 09:03 UTC, merged